name: Azure Static Web Apps CI/CD

on:
  push:
    branches:
      - main
  pull_request:
    types: [opened, synchronize, reopened, closed]
    branches:
      - main

jobs:
  build_and_deploy_job:
    if: github.event_name == 'push' || (github.event.action != 'closed' && github.event.pull_request.merged == false)
    runs-on: ubuntu-latest
    name: Build and Deploy Job
    permissions:
      id-token: write
      contents: read
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: true
          lfs: false

      # --- OIDC Client steps (keep as is, they are for authentication to Azure) ---
      - name: Install OIDC Client from Core Package
        run: npm install @actions/core@1.6.0 @actions/http-client
      - name: Get Id Token
        uses: actions/github-script@v6
        id: idtoken
        with:
          script: |
            const coredemo = require('@actions/core')
            return await coredemo.getIDToken()
          result-encoding: string
      # --- End OIDC Client steps ---

      # --- Explicit Node.js setup, npm install, and build steps ---
      - name: Set up Node.js environment
        uses: actions/setup-node@v3
        with:
          node-version: '22.x'

      - name: Install npm dependencies
        run: npm install --force # Added --force to ensure clean install, can remove if not needed

      - name: Debug: List all environment variables before build
        run: env | sort

      - name: Debug: List VITE_ prefixed environment variables before build
        run: env | grep VITE_ | sort

      - name: Build Frontend Application with Vite
        run: npm run build # This executes your Vite build command

      - name: Debug: Verify build output directory content
        run: ls -R dist # List contents of the 'dist' folder to ensure build happened

      # --- Deploy using Azure Static Web Apps Deploy Action ---
      - name: Deploy to Azure Static Web Apps
        id: builddeploy
        uses: Azure/static-web-apps-deploy@v1
        with:
          azure_static_web_apps_api_token: ${{ secrets.AZURE_STATIC_WEB_APPS_API_TOKEN_LEMON_PLANT_0E3B51D03 }}
          action: "upload"
          app_location: "/"
          api_location: ""
          output_location: "dist"
          # *** IMPORTANT CHANGES HERE ***
          # Remove app_build_command as we are now running it explicitly
          # app_build_command: "npm run build"
          skip_app_build: true # Tell the action that we've already built the app
          # *****************************
          github_id_token: ${{ steps.idtoken.outputs.result }}
          ###### End of Repository/Build Configurations ######

  close_pull_request_job:
    if: github.event_name == 'pull_request' && github.event.action == 'closed'
    runs-on: ubuntu-latest
    name: Close Pull Request Job
    steps:
      - name: Close Pull Request
        id: closepullrequest
        uses: Azure/static-web-apps-deploy@v1
        with:
          action: "close"
